-- AlterTable
ALTER TABLE "current_stock_part" ALTER COLUMN "pack_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "pack_date" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "history" ALTER COLUMN "pack_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "pack_date" SET DATA TYPE DATE,
ALTER COLUMN "unpack_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "unpack_date" SET DATA TYPE DATE;
